### PR TITLE
add local development override option similar to niv

### PR DESCRIPTION
**Pull request by thillux**

### CODE REVIEW

**Comment by andir** [comment]
Could you write some documentation (at least in the README.md) and add a test for this?

**Comment by thillux** [comment]
Sure (README.md) & I'll try (test).

**Comment by thillux** [comment]
> Could you write some documentation (at least in the README.md) and add a test for this?

@andir Both done.

**Comment by piegamesde** [comment]
What do you think of printing a trace warning for every override so that people don't accidentally run in to it?

**Comment by thillux** [comment]
> What do you think of printing a trace warning for every override so that people don't accidentally run in to it?

Done.

**Pull request merged**
