### PR TITLE
Add support for gitlab private repositories

### PR DESCRIPTION
**Pull request by dasJ**
We kind of need this

### CODE REVIEW

**Comment by piegamesde** [comment]
Thank you, this looks pretty solid. Some quite notes:

- If the token has other uses other than private repositories (e.g. rate limiting), maybe a more generic name like `auth_token` or `access_token` would be preferable?
- How does the Nix side fetcher handle this? That change is missing from the PR
- I'll have to think about that some more, but it's pretty likely that this will require incrementing the format version again.

**Comment by dasJ** [comment]
- I actually had the field named `access_token` during development but I changed it to `private_token`. This is [the relevant docs](https://docs.gitlab.com/ee/api/#personalprojectgroup-access-tokens) so if you want me to change it, I will
- The fetcher handles this as the `?private_token=…` is appended to the URL
- I **think** the format should be backwards compatible as older npins versions just ignore the field

**Comment by piegamesde** [comment]
Since the added field may be required for private repositories to successfully fetch, older versions can't really ignore it. Therefore, I'm in favor of incrementing the format version.

**Comment by andir** [comment]
Please don't forget to add unit tests for the new fields/logic in the GitLab case. We shouldn't let those fall behind. Especially if we can't (easily) have an integration tests those should be present.

**Comment by dasJ** [comment]
Added tests, added more docs, added token via environment, bumped the version

**Review by andir — APPROVED** [review]

**Comment by dasJ** [comment]
Andi mach release

**Comment by piegamesde** [comment]
piegames macht release

**Pull request merged**
